
package com.mycompany.practica4;

public class Vista extends javax.swing.JFrame {
    Escuderia escuderia[];
    int i = 0;

    public Vista() {
        initComponents();
        escuderia = new Escuderia[20];
        int i = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTPais = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JtPuntos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JtPosicion = new javax.swing.JTextField();
        BtAgregar = new javax.swing.JButton();
        BtBuscar = new javax.swing.JButton();
        BtEliminar = new javax.swing.JButton();
        BtLimpiar = new javax.swing.JButton();
        Nota = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(220, 47, 2));
        jLabel1.setText("ESCUDERIAS F1");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        JtNombre.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        JtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtNombreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        jLabel3.setText("Pais Origen:");

        JTPais.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        JTPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTPaisActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        jLabel4.setText("Puntos:");

        JtPuntos.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        JtPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtPuntosActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        jLabel5.setText("Posicion:");

        JtPosicion.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        JtPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtPosicionActionPerformed(evt);
            }
        });

        BtAgregar.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        BtAgregar.setForeground(new java.awt.Color(244, 140, 6));
        BtAgregar.setText("Agregar");
        BtAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAgregarActionPerformed(evt);
            }
        });

        BtBuscar.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        BtBuscar.setForeground(new java.awt.Color(244, 140, 6));
        BtBuscar.setText("Buscar");
        BtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarActionPerformed(evt);
            }
        });

        BtEliminar.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        BtEliminar.setForeground(new java.awt.Color(244, 140, 6));
        BtEliminar.setText("Eliminar");
        BtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEliminarActionPerformed(evt);
            }
        });

        BtLimpiar.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        BtLimpiar.setForeground(new java.awt.Color(244, 140, 6));
        BtLimpiar.setText("Limpiar");
        BtLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLimpiarActionPerformed(evt);
            }
        });

        Nota.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        Nota.setForeground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(JTPais)
                    .addComponent(JtPuntos)
                    .addComponent(JtPosicion))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(Nota, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtAgregar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JtPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtEliminar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JtPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtLimpiar))
                .addGap(18, 18, 18)
                .addComponent(Nota)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtNombreActionPerformed

    private void JTPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTPaisActionPerformed

    private void JtPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtPuntosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtPuntosActionPerformed

    private void JtPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtPosicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtPosicionActionPerformed

    private void BtAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAgregarActionPerformed
        // TODO add your handling code here:
       escuderia[i] = new Escuderia();
       escuderia[i].setNombreEs(JtNombre.getText());
       escuderia[i].setPaisEsc(JTPais.getText());
       escuderia[i].setPuntos(Integer.parseInt(JtPuntos.getText()));
       escuderia[i].setPosicionTablaConstructore(Integer.parseInt(JtPosicion.getText()));
       
       i++;
       JtNombre.setText("");
       JTPais.setText("");
       JtPuntos.setText("");
       JtPosicion.setText("");
       
        
    }//GEN-LAST:event_BtAgregarActionPerformed

    private void BtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEliminarActionPerformed
        // TODO add your handling code here:
         boolean encontrado = false;
        for (int k = 0; k < escuderia.length-1; k++) {
            if (escuderia[k] == null && escuderia[k+1] == null){
                break;
            }
            else if(escuderia[k].getNombreEs().equals(JtNombre.getText())){
                
                escuderia[k] = escuderia[k+1];
                Nota.setText("");
                encontrado = true;
            } 
        }
        if (encontrado == false) {
            Nota.setText("No se encontro");
        }
    }//GEN-LAST:event_BtEliminarActionPerformed

    private void BtLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLimpiarActionPerformed
        // TODO add your handling code here:
        JtNombre.setText("");
        JTPais.setText("");
        JtPuntos.setText("");
        JtPosicion.setText("");
        Nota.setText("");
    }//GEN-LAST:event_BtLimpiarActionPerformed

    private void BtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarActionPerformed
        // TODO add your handling code here:
        boolean encontrado = false;
        for (int k = 0; k < escuderia.length-1; k++) {
            if (escuderia[k] == null && escuderia[k+1] == null){
                break;
            }
            else if(escuderia[k].getNombreEs().equals(JtNombre.getText())){
                
                JtNombre.setText(escuderia[k].getNombreEs());
                JTPais.setText(escuderia[k].getPaisEsc());
                JtPuntos.setText(Integer.toString(escuderia[k].getPuntos()));
                JtPosicion.setText(Integer.toString(escuderia[k].getPosicionTablaConstructore()));
                Nota.setText("");
                encontrado = true;
            } 
        }
        if (encontrado == false) {
            Nota.setText("No se encontro");
        }
        
    }//GEN-LAST:event_BtBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAgregar;
    private javax.swing.JButton BtBuscar;
    private javax.swing.JButton BtEliminar;
    private javax.swing.JButton BtLimpiar;
    private javax.swing.JTextField JTPais;
    private javax.swing.JTextField JtNombre;
    private javax.swing.JTextField JtPosicion;
    private javax.swing.JTextField JtPuntos;
    private javax.swing.JLabel Nota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
